// Code generated by go-swagger; DO NOT EDIT.

package images

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"

	"docker_image_metadata_api/models"
)

// DeleteMetadataImageReader is a Reader for the DeleteMetadataImage structure.
type DeleteMetadataImageReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *DeleteMetadataImageReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewDeleteMetadataImageOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 500:
		result := NewDeleteMetadataImageInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewDeleteMetadataImageOK creates a DeleteMetadataImageOK with default headers values
func NewDeleteMetadataImageOK() *DeleteMetadataImageOK {
	return &DeleteMetadataImageOK{}
}

/* DeleteMetadataImageOK describes a response with status code 200, with default header values.

Removed successfully
*/
type DeleteMetadataImageOK struct {
}

func (o *DeleteMetadataImageOK) Error() string {
	return fmt.Sprintf("[DELETE /metadata/image][%d] deleteMetadataImageOK ", 200)
}

func (o *DeleteMetadataImageOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewDeleteMetadataImageInternalServerError creates a DeleteMetadataImageInternalServerError with default headers values
func NewDeleteMetadataImageInternalServerError() *DeleteMetadataImageInternalServerError {
	return &DeleteMetadataImageInternalServerError{}
}

/* DeleteMetadataImageInternalServerError describes a response with status code 500, with default header values.

Internal Error Message
*/
type DeleteMetadataImageInternalServerError struct {
	Payload *models.ErrorResponse
}

func (o *DeleteMetadataImageInternalServerError) Error() string {
	return fmt.Sprintf("[DELETE /metadata/image][%d] deleteMetadataImageInternalServerError  %+v", 500, o.Payload)
}
func (o *DeleteMetadataImageInternalServerError) GetPayload() *models.ErrorResponse {
	return o.Payload
}

func (o *DeleteMetadataImageInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

/*DeleteMetadataImageBody delete metadata image body
swagger:model DeleteMetadataImageBody
*/
type DeleteMetadataImageBody struct {

	// image name
	ImageName string `json:"ImageName,omitempty"`
}

// Validate validates this delete metadata image body
func (o *DeleteMetadataImageBody) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this delete metadata image body based on context it is used
func (o *DeleteMetadataImageBody) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (o *DeleteMetadataImageBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *DeleteMetadataImageBody) UnmarshalBinary(b []byte) error {
	var res DeleteMetadataImageBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}
