// Code generated by go-swagger; DO NOT EDIT.

package images

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetMetadataImageParams creates a new GetMetadataImageParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetMetadataImageParams() *GetMetadataImageParams {
	return &GetMetadataImageParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetMetadataImageParamsWithTimeout creates a new GetMetadataImageParams object
// with the ability to set a timeout on a request.
func NewGetMetadataImageParamsWithTimeout(timeout time.Duration) *GetMetadataImageParams {
	return &GetMetadataImageParams{
		timeout: timeout,
	}
}

// NewGetMetadataImageParamsWithContext creates a new GetMetadataImageParams object
// with the ability to set a context for a request.
func NewGetMetadataImageParamsWithContext(ctx context.Context) *GetMetadataImageParams {
	return &GetMetadataImageParams{
		Context: ctx,
	}
}

// NewGetMetadataImageParamsWithHTTPClient creates a new GetMetadataImageParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetMetadataImageParamsWithHTTPClient(client *http.Client) *GetMetadataImageParams {
	return &GetMetadataImageParams{
		HTTPClient: client,
	}
}

/* GetMetadataImageParams contains all the parameters to send to the API endpoint
   for the get metadata image operation.

   Typically these are written to a http.Request.
*/
type GetMetadataImageParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get metadata image params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetMetadataImageParams) WithDefaults() *GetMetadataImageParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get metadata image params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetMetadataImageParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get metadata image params
func (o *GetMetadataImageParams) WithTimeout(timeout time.Duration) *GetMetadataImageParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get metadata image params
func (o *GetMetadataImageParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get metadata image params
func (o *GetMetadataImageParams) WithContext(ctx context.Context) *GetMetadataImageParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get metadata image params
func (o *GetMetadataImageParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get metadata image params
func (o *GetMetadataImageParams) WithHTTPClient(client *http.Client) *GetMetadataImageParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get metadata image params
func (o *GetMetadataImageParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *GetMetadataImageParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
