// Code generated by go-swagger; DO NOT EDIT.

package images

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"docker_image_metadata_api/models"
)

// GetMetadataImageReader is a Reader for the GetMetadataImage structure.
type GetMetadataImageReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetMetadataImageReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetMetadataImageOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 500:
		result := NewGetMetadataImageInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewGetMetadataImageOK creates a GetMetadataImageOK with default headers values
func NewGetMetadataImageOK() *GetMetadataImageOK {
	return &GetMetadataImageOK{}
}

/* GetMetadataImageOK describes a response with status code 200, with default header values.

List of registered images in the metadata service
*/
type GetMetadataImageOK struct {
	Payload models.ListOfImages
}

func (o *GetMetadataImageOK) Error() string {
	return fmt.Sprintf("[GET /metadata/image][%d] getMetadataImageOK  %+v", 200, o.Payload)
}
func (o *GetMetadataImageOK) GetPayload() models.ListOfImages {
	return o.Payload
}

func (o *GetMetadataImageOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetMetadataImageInternalServerError creates a GetMetadataImageInternalServerError with default headers values
func NewGetMetadataImageInternalServerError() *GetMetadataImageInternalServerError {
	return &GetMetadataImageInternalServerError{}
}

/* GetMetadataImageInternalServerError describes a response with status code 500, with default header values.

Internal Error Message
*/
type GetMetadataImageInternalServerError struct {
	Payload *models.ErrorResponse
}

func (o *GetMetadataImageInternalServerError) Error() string {
	return fmt.Sprintf("[GET /metadata/image][%d] getMetadataImageInternalServerError  %+v", 500, o.Payload)
}
func (o *GetMetadataImageInternalServerError) GetPayload() *models.ErrorResponse {
	return o.Payload
}

func (o *GetMetadataImageInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
