// Code generated by go-swagger; DO NOT EDIT.

package images

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewPostMetadataImageParams creates a new PostMetadataImageParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewPostMetadataImageParams() *PostMetadataImageParams {
	return &PostMetadataImageParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewPostMetadataImageParamsWithTimeout creates a new PostMetadataImageParams object
// with the ability to set a timeout on a request.
func NewPostMetadataImageParamsWithTimeout(timeout time.Duration) *PostMetadataImageParams {
	return &PostMetadataImageParams{
		timeout: timeout,
	}
}

// NewPostMetadataImageParamsWithContext creates a new PostMetadataImageParams object
// with the ability to set a context for a request.
func NewPostMetadataImageParamsWithContext(ctx context.Context) *PostMetadataImageParams {
	return &PostMetadataImageParams{
		Context: ctx,
	}
}

// NewPostMetadataImageParamsWithHTTPClient creates a new PostMetadataImageParams object
// with the ability to set a custom HTTPClient for a request.
func NewPostMetadataImageParamsWithHTTPClient(client *http.Client) *PostMetadataImageParams {
	return &PostMetadataImageParams{
		HTTPClient: client,
	}
}

/* PostMetadataImageParams contains all the parameters to send to the API endpoint
   for the post metadata image operation.

   Typically these are written to a http.Request.
*/
type PostMetadataImageParams struct {

	// ImageName.
	ImageName PostMetadataImageBody

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the post metadata image params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PostMetadataImageParams) WithDefaults() *PostMetadataImageParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the post metadata image params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PostMetadataImageParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the post metadata image params
func (o *PostMetadataImageParams) WithTimeout(timeout time.Duration) *PostMetadataImageParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the post metadata image params
func (o *PostMetadataImageParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the post metadata image params
func (o *PostMetadataImageParams) WithContext(ctx context.Context) *PostMetadataImageParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the post metadata image params
func (o *PostMetadataImageParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the post metadata image params
func (o *PostMetadataImageParams) WithHTTPClient(client *http.Client) *PostMetadataImageParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the post metadata image params
func (o *PostMetadataImageParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithImageName adds the imageName to the post metadata image params
func (o *PostMetadataImageParams) WithImageName(imageName PostMetadataImageBody) *PostMetadataImageParams {
	o.SetImageName(imageName)
	return o
}

// SetImageName adds the imageName to the post metadata image params
func (o *PostMetadataImageParams) SetImageName(imageName PostMetadataImageBody) {
	o.ImageName = imageName
}

// WriteToRequest writes these params to a swagger request
func (o *PostMetadataImageParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if err := r.SetBodyParam(o.ImageName); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
