// Code generated by go-swagger; DO NOT EDIT.

package tags

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"

	"docker_image_metadata_api/models"
)

// DeleteMetadataImageImagenameReader is a Reader for the DeleteMetadataImageImagename structure.
type DeleteMetadataImageImagenameReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *DeleteMetadataImageImagenameReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 201:
		result := NewDeleteMetadataImageImagenameCreated()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 500:
		result := NewDeleteMetadataImageImagenameInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewDeleteMetadataImageImagenameCreated creates a DeleteMetadataImageImagenameCreated with default headers values
func NewDeleteMetadataImageImagenameCreated() *DeleteMetadataImageImagenameCreated {
	return &DeleteMetadataImageImagenameCreated{}
}

/* DeleteMetadataImageImagenameCreated describes a response with status code 201, with default header values.

Created
*/
type DeleteMetadataImageImagenameCreated struct {
}

func (o *DeleteMetadataImageImagenameCreated) Error() string {
	return fmt.Sprintf("[DELETE /metadata/image/{imagename}][%d] deleteMetadataImageImagenameCreated ", 201)
}

func (o *DeleteMetadataImageImagenameCreated) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewDeleteMetadataImageImagenameInternalServerError creates a DeleteMetadataImageImagenameInternalServerError with default headers values
func NewDeleteMetadataImageImagenameInternalServerError() *DeleteMetadataImageImagenameInternalServerError {
	return &DeleteMetadataImageImagenameInternalServerError{}
}

/* DeleteMetadataImageImagenameInternalServerError describes a response with status code 500, with default header values.

Internal Error Message
*/
type DeleteMetadataImageImagenameInternalServerError struct {
	Payload *models.ErrorResponse
}

func (o *DeleteMetadataImageImagenameInternalServerError) Error() string {
	return fmt.Sprintf("[DELETE /metadata/image/{imagename}][%d] deleteMetadataImageImagenameInternalServerError  %+v", 500, o.Payload)
}
func (o *DeleteMetadataImageImagenameInternalServerError) GetPayload() *models.ErrorResponse {
	return o.Payload
}

func (o *DeleteMetadataImageImagenameInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

/*DeleteMetadataImageImagenameBody delete metadata image imagename body
swagger:model DeleteMetadataImageImagenameBody
*/
type DeleteMetadataImageImagenameBody struct {

	// tag name
	TagName string `json:"TagName,omitempty"`
}

// Validate validates this delete metadata image imagename body
func (o *DeleteMetadataImageImagenameBody) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this delete metadata image imagename body based on context it is used
func (o *DeleteMetadataImageImagenameBody) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (o *DeleteMetadataImageImagenameBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *DeleteMetadataImageImagenameBody) UnmarshalBinary(b []byte) error {
	var res DeleteMetadataImageImagenameBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}
