// Code generated by go-swagger; DO NOT EDIT.

package tags

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetMetadataImageImagenameParams creates a new GetMetadataImageImagenameParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetMetadataImageImagenameParams() *GetMetadataImageImagenameParams {
	return &GetMetadataImageImagenameParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetMetadataImageImagenameParamsWithTimeout creates a new GetMetadataImageImagenameParams object
// with the ability to set a timeout on a request.
func NewGetMetadataImageImagenameParamsWithTimeout(timeout time.Duration) *GetMetadataImageImagenameParams {
	return &GetMetadataImageImagenameParams{
		timeout: timeout,
	}
}

// NewGetMetadataImageImagenameParamsWithContext creates a new GetMetadataImageImagenameParams object
// with the ability to set a context for a request.
func NewGetMetadataImageImagenameParamsWithContext(ctx context.Context) *GetMetadataImageImagenameParams {
	return &GetMetadataImageImagenameParams{
		Context: ctx,
	}
}

// NewGetMetadataImageImagenameParamsWithHTTPClient creates a new GetMetadataImageImagenameParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetMetadataImageImagenameParamsWithHTTPClient(client *http.Client) *GetMetadataImageImagenameParams {
	return &GetMetadataImageImagenameParams{
		HTTPClient: client,
	}
}

/* GetMetadataImageImagenameParams contains all the parameters to send to the API endpoint
   for the get metadata image imagename operation.

   Typically these are written to a http.Request.
*/
type GetMetadataImageImagenameParams struct {

	// Imagename.
	Imagename string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get metadata image imagename params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetMetadataImageImagenameParams) WithDefaults() *GetMetadataImageImagenameParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get metadata image imagename params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetMetadataImageImagenameParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get metadata image imagename params
func (o *GetMetadataImageImagenameParams) WithTimeout(timeout time.Duration) *GetMetadataImageImagenameParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get metadata image imagename params
func (o *GetMetadataImageImagenameParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get metadata image imagename params
func (o *GetMetadataImageImagenameParams) WithContext(ctx context.Context) *GetMetadataImageImagenameParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get metadata image imagename params
func (o *GetMetadataImageImagenameParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get metadata image imagename params
func (o *GetMetadataImageImagenameParams) WithHTTPClient(client *http.Client) *GetMetadataImageImagenameParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get metadata image imagename params
func (o *GetMetadataImageImagenameParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithImagename adds the imagename to the get metadata image imagename params
func (o *GetMetadataImageImagenameParams) WithImagename(imagename string) *GetMetadataImageImagenameParams {
	o.SetImagename(imagename)
	return o
}

// SetImagename adds the imagename to the get metadata image imagename params
func (o *GetMetadataImageImagenameParams) SetImagename(imagename string) {
	o.Imagename = imagename
}

// WriteToRequest writes these params to a swagger request
func (o *GetMetadataImageImagenameParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param imagename
	if err := r.SetPathParam("imagename", o.Imagename); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
