// Code generated by go-swagger; DO NOT EDIT.

package tags

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewPostMetadataImageImagenameParams creates a new PostMetadataImageImagenameParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewPostMetadataImageImagenameParams() *PostMetadataImageImagenameParams {
	return &PostMetadataImageImagenameParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewPostMetadataImageImagenameParamsWithTimeout creates a new PostMetadataImageImagenameParams object
// with the ability to set a timeout on a request.
func NewPostMetadataImageImagenameParamsWithTimeout(timeout time.Duration) *PostMetadataImageImagenameParams {
	return &PostMetadataImageImagenameParams{
		timeout: timeout,
	}
}

// NewPostMetadataImageImagenameParamsWithContext creates a new PostMetadataImageImagenameParams object
// with the ability to set a context for a request.
func NewPostMetadataImageImagenameParamsWithContext(ctx context.Context) *PostMetadataImageImagenameParams {
	return &PostMetadataImageImagenameParams{
		Context: ctx,
	}
}

// NewPostMetadataImageImagenameParamsWithHTTPClient creates a new PostMetadataImageImagenameParams object
// with the ability to set a custom HTTPClient for a request.
func NewPostMetadataImageImagenameParamsWithHTTPClient(client *http.Client) *PostMetadataImageImagenameParams {
	return &PostMetadataImageImagenameParams{
		HTTPClient: client,
	}
}

/* PostMetadataImageImagenameParams contains all the parameters to send to the API endpoint
   for the post metadata image imagename operation.

   Typically these are written to a http.Request.
*/
type PostMetadataImageImagenameParams struct {

	// TagName.
	TagName PostMetadataImageImagenameBody

	// Imagename.
	Imagename string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the post metadata image imagename params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PostMetadataImageImagenameParams) WithDefaults() *PostMetadataImageImagenameParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the post metadata image imagename params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PostMetadataImageImagenameParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the post metadata image imagename params
func (o *PostMetadataImageImagenameParams) WithTimeout(timeout time.Duration) *PostMetadataImageImagenameParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the post metadata image imagename params
func (o *PostMetadataImageImagenameParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the post metadata image imagename params
func (o *PostMetadataImageImagenameParams) WithContext(ctx context.Context) *PostMetadataImageImagenameParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the post metadata image imagename params
func (o *PostMetadataImageImagenameParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the post metadata image imagename params
func (o *PostMetadataImageImagenameParams) WithHTTPClient(client *http.Client) *PostMetadataImageImagenameParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the post metadata image imagename params
func (o *PostMetadataImageImagenameParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithTagName adds the tagName to the post metadata image imagename params
func (o *PostMetadataImageImagenameParams) WithTagName(tagName PostMetadataImageImagenameBody) *PostMetadataImageImagenameParams {
	o.SetTagName(tagName)
	return o
}

// SetTagName adds the tagName to the post metadata image imagename params
func (o *PostMetadataImageImagenameParams) SetTagName(tagName PostMetadataImageImagenameBody) {
	o.TagName = tagName
}

// WithImagename adds the imagename to the post metadata image imagename params
func (o *PostMetadataImageImagenameParams) WithImagename(imagename string) *PostMetadataImageImagenameParams {
	o.SetImagename(imagename)
	return o
}

// SetImagename adds the imagename to the post metadata image imagename params
func (o *PostMetadataImageImagenameParams) SetImagename(imagename string) {
	o.Imagename = imagename
}

// WriteToRequest writes these params to a swagger request
func (o *PostMetadataImageImagenameParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if err := r.SetBodyParam(o.TagName); err != nil {
		return err
	}

	// path param imagename
	if err := r.SetPathParam("imagename", o.Imagename); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
