// Code generated by go-swagger; DO NOT EDIT.

package restapi

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
)

var (
	// SwaggerJSON embedded version of the swagger document used at generation time
	SwaggerJSON json.RawMessage
	// FlatSwaggerJSON embedded flattened version of the swagger document used at generation time
	FlatSwaggerJSON json.RawMessage
)

func init() {
	SwaggerJSON = json.RawMessage([]byte(`{
  "consumes": [
    "application/json"
  ],
  "produces": [
    "application/json"
  ],
  "schemes": [
    "http"
  ],
  "swagger": "2.0",
  "info": {
    "title": "Docker image metadata API",
    "version": "0.0.1"
  },
  "paths": {
    "/metadata": {
      "post": {
        "description": "Register and verify if the image exists in docker registry",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "tags": [
          "ImageTag"
        ],
        "summary": "Register image with tag",
        "parameters": [
          {
            "name": "Image",
            "in": "body",
            "schema": {
              "type": "object",
              "properties": {
                "ImageName": {
                  "type": "string"
                },
                "TagName": {
                  "type": "string"
                }
              }
            }
          }
        ],
        "responses": {
          "201": {
            "description": "Created"
          },
          "409": {
            "description": "Image already exists",
            "schema": {
              "$ref": "#/definitions/ConflictResponse"
            }
          },
          "424": {
            "description": "Failed Dependency",
            "schema": {
              "$ref": "#/definitions/FailedDependency"
            }
          },
          "500": {
            "description": "Internal Error Message",
            "schema": {
              "$ref": "#/definitions/ErrorResponse"
            }
          }
        }
      }
    },
    "/metadata/image": {
      "post": {
        "produces": [
          "application/json"
        ],
        "tags": [
          "ImageTag"
        ],
        "summary": "List of registered image tags in the metadata service",
        "parameters": [
          {
            "name": "Image",
            "in": "body",
            "schema": {
              "type": "object",
              "properties": {
                "ImageName": {
                  "type": "string"
                }
              }
            }
          }
        ],
        "responses": {
          "200": {
            "description": "List of registered image tags in the metadata service",
            "schema": {
              "type": "array",
              "items": {
                "type": "string"
              }
            }
          },
          "404": {
            "description": "Image with tag not found",
            "schema": {
              "$ref": "#/definitions/NotFoundResponse"
            }
          },
          "500": {
            "description": "Internal Error Message",
            "schema": {
              "$ref": "#/definitions/ErrorResponse"
            }
          }
        }
      },
      "delete": {
        "description": "All tags and metadata will be removed",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "tags": [
          "Image"
        ],
        "summary": "Unregister image from metadata database",
        "parameters": [
          {
            "name": "Image",
            "in": "body",
            "schema": {
              "type": "object",
              "properties": {
                "ImageName": {
                  "type": "string"
                }
              }
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Removed successfully",
            "schema": {
              "description": "List of removed tags",
              "type": "array",
              "items": {
                "type": "string"
              }
            }
          },
          "404": {
            "description": "Any image not found in database",
            "schema": {
              "$ref": "#/definitions/NotFoundResponse"
            }
          },
          "500": {
            "description": "Internal Error Message",
            "schema": {
              "$ref": "#/definitions/ErrorResponse"
            }
          }
        }
      }
    },
    "/metadata/image/tag": {
      "post": {
        "tags": [
          "Metadata"
        ],
        "summary": "Get metadata",
        "parameters": [
          {
            "name": "Image",
            "in": "body",
            "schema": {
              "type": "object",
              "properties": {
                "ImageName": {
                  "type": "string"
                },
                "TagName": {
                  "type": "string"
                }
              }
            }
          }
        ],
        "responses": {
          "200": {
            "description": "List of registered image tags in the metadata service",
            "schema": {
              "$ref": "#/definitions/Metadata"
            }
          },
          "404": {
            "description": "Image with tag not found",
            "schema": {
              "$ref": "#/definitions/NotFoundResponse"
            }
          },
          "500": {
            "description": "Internal Error Message",
            "schema": {
              "$ref": "#/definitions/ErrorResponse"
            }
          }
        }
      },
      "delete": {
        "description": "Remove tag and all its metadata",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "tags": [
          "ImageTag"
        ],
        "summary": "Remove tag",
        "parameters": [
          {
            "name": "Image",
            "in": "body",
            "schema": {
              "type": "object",
              "properties": {
                "ImageName": {
                  "type": "string"
                },
                "TagName": {
                  "type": "string"
                }
              }
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Erased"
          },
          "404": {
            "description": "Image with tag not found",
            "schema": {
              "$ref": "#/definitions/NotFoundResponse"
            }
          },
          "500": {
            "description": "Internal Error Message",
            "schema": {
              "$ref": "#/definitions/ErrorResponse"
            }
          }
        }
      }
    },
    "/metadata/image/tag/keys": {
      "put": {
        "description": "Update default value of specified key",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "tags": [
          "Metadata"
        ],
        "summary": "Update default value of specified key",
        "parameters": [
          {
            "name": "Image",
            "in": "body",
            "schema": {
              "type": "object",
              "properties": {
                "Value": {
                  "type": "string"
                },
                "ImageName": {
                  "type": "string"
                },
                "Key": {
                  "type": "string"
                },
                "TagName": {
                  "type": "string"
                }
              }
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Successfully updated"
          },
          "404": {
            "description": "Not Found",
            "schema": {
              "$ref": "#/definitions/NotFoundResponse"
            }
          },
          "500": {
            "description": "Internal Error Message",
            "schema": {
              "$ref": "#/definitions/ErrorResponse"
            }
          }
        }
      },
      "post": {
        "description": "Create new metadata key and (optional) new default value",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "tags": [
          "Metadata"
        ],
        "summary": "Create new key in metadata",
        "parameters": [
          {
            "name": "Image",
            "in": "body",
            "schema": {
              "type": "object",
              "properties": {
                "Value": {
                  "type": "string",
                  "x-nullable": true
                },
                "ImageName": {
                  "type": "string"
                },
                "Key": {
                  "type": "string"
                },
                "TagName": {
                  "type": "string"
                }
              }
            }
          }
        ],
        "responses": {
          "201": {
            "description": "Created"
          },
          "404": {
            "description": "Image with tag not found",
            "schema": {
              "$ref": "#/definitions/NotFoundResponse"
            }
          },
          "409": {
            "description": "Key already exists",
            "schema": {
              "$ref": "#/definitions/ConflictResponse"
            }
          },
          "500": {
            "description": "Internal Error Message",
            "schema": {
              "$ref": "#/definitions/ErrorResponse"
            }
          }
        }
      },
      "delete": {
        "description": "Remove metadata key",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "tags": [
          "Metadata"
        ],
        "summary": "Remove key from metadata",
        "parameters": [
          {
            "name": "Image",
            "in": "body",
            "schema": {
              "type": "object",
              "properties": {
                "ImageName": {
                  "type": "string"
                },
                "Key": {
                  "type": "string"
                },
                "TagName": {
                  "type": "string"
                }
              }
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Successfully removed"
          },
          "404": {
            "description": "Not Found",
            "schema": {
              "$ref": "#/definitions/NotFoundResponse"
            }
          },
          "500": {
            "description": "Internal Error Message",
            "schema": {
              "$ref": "#/definitions/ErrorResponse"
            }
          }
        }
      }
    },
    "/metadata/images": {
      "get": {
        "produces": [
          "application/json"
        ],
        "tags": [
          "Image"
        ],
        "summary": "List of registered images in the metadata service",
        "responses": {
          "200": {
            "description": "List of registered images in the metadata service",
            "schema": {
              "$ref": "#/definitions/ListOfImages"
            }
          },
          "500": {
            "description": "Internal Error Message",
            "schema": {
              "$ref": "#/definitions/ErrorResponse"
            }
          }
        }
      }
    }
  },
  "definitions": {
    "ConflictResponse": {
      "type": "object",
      "properties": {
        "Message": {
          "type": "string"
        }
      }
    },
    "DeletedKeyResponse": {
      "type": "object",
      "properties": {
        "Image": {
          "type": "string"
        },
        "Key": {
          "type": "string"
        },
        "Tag": {
          "type": "string"
        }
      }
    },
    "DeletedTagResponse": {
      "type": "object",
      "properties": {
        "Image": {
          "type": "string"
        },
        "Message": {
          "type": "string"
        },
        "Tag": {
          "type": "string"
        }
      }
    },
    "ErrorResponse": {
      "type": "object",
      "properties": {
        "Message": {
          "type": "string"
        }
      }
    },
    "FailedDependency": {
      "type": "object",
      "properties": {
        "Message": {
          "type": "string"
        }
      }
    },
    "ListOfImages": {
      "type": "array",
      "items": {
        "type": "string"
      }
    },
    "Metadata": {
      "type": "array",
      "items": {
        "$ref": "#/definitions/MetadataObj"
      }
    },
    "MetadataObj": {
      "type": "object",
      "properties": {
        "Value": {
          "x-go-type": "sql.NullString",
          "x-nullable": true
        },
        "Key": {
          "type": "string"
        }
      }
    },
    "NotFoundResponse": {
      "type": "object",
      "properties": {
        "Message": {
          "type": "string"
        }
      }
    },
    "Tags": {
      "type": "array",
      "items": {
        "type": "string"
      }
    }
  }
}`))
	FlatSwaggerJSON = json.RawMessage([]byte(`{
  "consumes": [
    "application/json"
  ],
  "produces": [
    "application/json"
  ],
  "schemes": [
    "http"
  ],
  "swagger": "2.0",
  "info": {
    "title": "Docker image metadata API",
    "version": "0.0.1"
  },
  "paths": {
    "/metadata": {
      "post": {
        "description": "Register and verify if the image exists in docker registry",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "tags": [
          "ImageTag"
        ],
        "summary": "Register image with tag",
        "parameters": [
          {
            "name": "Image",
            "in": "body",
            "schema": {
              "type": "object",
              "properties": {
                "ImageName": {
                  "type": "string"
                },
                "TagName": {
                  "type": "string"
                }
              }
            }
          }
        ],
        "responses": {
          "201": {
            "description": "Created"
          },
          "409": {
            "description": "Image already exists",
            "schema": {
              "$ref": "#/definitions/ConflictResponse"
            }
          },
          "424": {
            "description": "Failed Dependency",
            "schema": {
              "$ref": "#/definitions/FailedDependency"
            }
          },
          "500": {
            "description": "Internal Error Message",
            "schema": {
              "$ref": "#/definitions/ErrorResponse"
            }
          }
        }
      }
    },
    "/metadata/image": {
      "post": {
        "produces": [
          "application/json"
        ],
        "tags": [
          "ImageTag"
        ],
        "summary": "List of registered image tags in the metadata service",
        "parameters": [
          {
            "name": "Image",
            "in": "body",
            "schema": {
              "type": "object",
              "properties": {
                "ImageName": {
                  "type": "string"
                }
              }
            }
          }
        ],
        "responses": {
          "200": {
            "description": "List of registered image tags in the metadata service",
            "schema": {
              "type": "array",
              "items": {
                "type": "string"
              }
            }
          },
          "404": {
            "description": "Image with tag not found",
            "schema": {
              "$ref": "#/definitions/NotFoundResponse"
            }
          },
          "500": {
            "description": "Internal Error Message",
            "schema": {
              "$ref": "#/definitions/ErrorResponse"
            }
          }
        }
      },
      "delete": {
        "description": "All tags and metadata will be removed",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "tags": [
          "Image"
        ],
        "summary": "Unregister image from metadata database",
        "parameters": [
          {
            "name": "Image",
            "in": "body",
            "schema": {
              "type": "object",
              "properties": {
                "ImageName": {
                  "type": "string"
                }
              }
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Removed successfully",
            "schema": {
              "description": "List of removed tags",
              "type": "array",
              "items": {
                "type": "string"
              }
            }
          },
          "404": {
            "description": "Any image not found in database",
            "schema": {
              "$ref": "#/definitions/NotFoundResponse"
            }
          },
          "500": {
            "description": "Internal Error Message",
            "schema": {
              "$ref": "#/definitions/ErrorResponse"
            }
          }
        }
      }
    },
    "/metadata/image/tag": {
      "post": {
        "tags": [
          "Metadata"
        ],
        "summary": "Get metadata",
        "parameters": [
          {
            "name": "Image",
            "in": "body",
            "schema": {
              "type": "object",
              "properties": {
                "ImageName": {
                  "type": "string"
                },
                "TagName": {
                  "type": "string"
                }
              }
            }
          }
        ],
        "responses": {
          "200": {
            "description": "List of registered image tags in the metadata service",
            "schema": {
              "$ref": "#/definitions/Metadata"
            }
          },
          "404": {
            "description": "Image with tag not found",
            "schema": {
              "$ref": "#/definitions/NotFoundResponse"
            }
          },
          "500": {
            "description": "Internal Error Message",
            "schema": {
              "$ref": "#/definitions/ErrorResponse"
            }
          }
        }
      },
      "delete": {
        "description": "Remove tag and all its metadata",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "tags": [
          "ImageTag"
        ],
        "summary": "Remove tag",
        "parameters": [
          {
            "name": "Image",
            "in": "body",
            "schema": {
              "type": "object",
              "properties": {
                "ImageName": {
                  "type": "string"
                },
                "TagName": {
                  "type": "string"
                }
              }
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Erased"
          },
          "404": {
            "description": "Image with tag not found",
            "schema": {
              "$ref": "#/definitions/NotFoundResponse"
            }
          },
          "500": {
            "description": "Internal Error Message",
            "schema": {
              "$ref": "#/definitions/ErrorResponse"
            }
          }
        }
      }
    },
    "/metadata/image/tag/keys": {
      "put": {
        "description": "Update default value of specified key",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "tags": [
          "Metadata"
        ],
        "summary": "Update default value of specified key",
        "parameters": [
          {
            "name": "Image",
            "in": "body",
            "schema": {
              "type": "object",
              "properties": {
                "Value": {
                  "type": "string"
                },
                "ImageName": {
                  "type": "string"
                },
                "Key": {
                  "type": "string"
                },
                "TagName": {
                  "type": "string"
                }
              }
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Successfully updated"
          },
          "404": {
            "description": "Not Found",
            "schema": {
              "$ref": "#/definitions/NotFoundResponse"
            }
          },
          "500": {
            "description": "Internal Error Message",
            "schema": {
              "$ref": "#/definitions/ErrorResponse"
            }
          }
        }
      },
      "post": {
        "description": "Create new metadata key and (optional) new default value",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "tags": [
          "Metadata"
        ],
        "summary": "Create new key in metadata",
        "parameters": [
          {
            "name": "Image",
            "in": "body",
            "schema": {
              "type": "object",
              "properties": {
                "Value": {
                  "type": "string",
                  "x-nullable": true
                },
                "ImageName": {
                  "type": "string"
                },
                "Key": {
                  "type": "string"
                },
                "TagName": {
                  "type": "string"
                }
              }
            }
          }
        ],
        "responses": {
          "201": {
            "description": "Created"
          },
          "404": {
            "description": "Image with tag not found",
            "schema": {
              "$ref": "#/definitions/NotFoundResponse"
            }
          },
          "409": {
            "description": "Key already exists",
            "schema": {
              "$ref": "#/definitions/ConflictResponse"
            }
          },
          "500": {
            "description": "Internal Error Message",
            "schema": {
              "$ref": "#/definitions/ErrorResponse"
            }
          }
        }
      },
      "delete": {
        "description": "Remove metadata key",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "tags": [
          "Metadata"
        ],
        "summary": "Remove key from metadata",
        "parameters": [
          {
            "name": "Image",
            "in": "body",
            "schema": {
              "type": "object",
              "properties": {
                "ImageName": {
                  "type": "string"
                },
                "Key": {
                  "type": "string"
                },
                "TagName": {
                  "type": "string"
                }
              }
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Successfully removed"
          },
          "404": {
            "description": "Not Found",
            "schema": {
              "$ref": "#/definitions/NotFoundResponse"
            }
          },
          "500": {
            "description": "Internal Error Message",
            "schema": {
              "$ref": "#/definitions/ErrorResponse"
            }
          }
        }
      }
    },
    "/metadata/images": {
      "get": {
        "produces": [
          "application/json"
        ],
        "tags": [
          "Image"
        ],
        "summary": "List of registered images in the metadata service",
        "responses": {
          "200": {
            "description": "List of registered images in the metadata service",
            "schema": {
              "$ref": "#/definitions/ListOfImages"
            }
          },
          "500": {
            "description": "Internal Error Message",
            "schema": {
              "$ref": "#/definitions/ErrorResponse"
            }
          }
        }
      }
    }
  },
  "definitions": {
    "ConflictResponse": {
      "type": "object",
      "properties": {
        "Message": {
          "type": "string"
        }
      }
    },
    "DeletedKeyResponse": {
      "type": "object",
      "properties": {
        "Image": {
          "type": "string"
        },
        "Key": {
          "type": "string"
        },
        "Tag": {
          "type": "string"
        }
      }
    },
    "DeletedTagResponse": {
      "type": "object",
      "properties": {
        "Image": {
          "type": "string"
        },
        "Message": {
          "type": "string"
        },
        "Tag": {
          "type": "string"
        }
      }
    },
    "ErrorResponse": {
      "type": "object",
      "properties": {
        "Message": {
          "type": "string"
        }
      }
    },
    "FailedDependency": {
      "type": "object",
      "properties": {
        "Message": {
          "type": "string"
        }
      }
    },
    "ListOfImages": {
      "type": "array",
      "items": {
        "type": "string"
      }
    },
    "Metadata": {
      "type": "array",
      "items": {
        "$ref": "#/definitions/MetadataObj"
      }
    },
    "MetadataObj": {
      "type": "object",
      "properties": {
        "Value": {
          "x-go-type": "sql.NullString",
          "x-nullable": true
        },
        "Key": {
          "type": "string"
        }
      }
    },
    "NotFoundResponse": {
      "type": "object",
      "properties": {
        "Message": {
          "type": "string"
        }
      }
    },
    "Tags": {
      "type": "array",
      "items": {
        "type": "string"
      }
    }
  }
}`))
}
