// Code generated by go-swagger; DO NOT EDIT.

package metadata

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"

	"docker_image_metadata_api/models"
)

// DeleteMetadataTagTagImageImagenameReader is a Reader for the DeleteMetadataTagTagImageImagename structure.
type DeleteMetadataTagTagImageImagenameReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *DeleteMetadataTagTagImageImagenameReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewDeleteMetadataTagTagImageImagenameOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 500:
		result := NewDeleteMetadataTagTagImageImagenameInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewDeleteMetadataTagTagImageImagenameOK creates a DeleteMetadataTagTagImageImagenameOK with default headers values
func NewDeleteMetadataTagTagImageImagenameOK() *DeleteMetadataTagTagImageImagenameOK {
	return &DeleteMetadataTagTagImageImagenameOK{}
}

/* DeleteMetadataTagTagImageImagenameOK describes a response with status code 200, with default header values.

Successfully removed
*/
type DeleteMetadataTagTagImageImagenameOK struct {
}

func (o *DeleteMetadataTagTagImageImagenameOK) Error() string {
	return fmt.Sprintf("[DELETE /metadata/tag/{tag}/image/{imagename}][%d] deleteMetadataTagTagImageImagenameOK ", 200)
}

func (o *DeleteMetadataTagTagImageImagenameOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewDeleteMetadataTagTagImageImagenameInternalServerError creates a DeleteMetadataTagTagImageImagenameInternalServerError with default headers values
func NewDeleteMetadataTagTagImageImagenameInternalServerError() *DeleteMetadataTagTagImageImagenameInternalServerError {
	return &DeleteMetadataTagTagImageImagenameInternalServerError{}
}

/* DeleteMetadataTagTagImageImagenameInternalServerError describes a response with status code 500, with default header values.

Internal Error Message
*/
type DeleteMetadataTagTagImageImagenameInternalServerError struct {
	Payload *models.ErrorResponse
}

func (o *DeleteMetadataTagTagImageImagenameInternalServerError) Error() string {
	return fmt.Sprintf("[DELETE /metadata/tag/{tag}/image/{imagename}][%d] deleteMetadataTagTagImageImagenameInternalServerError  %+v", 500, o.Payload)
}
func (o *DeleteMetadataTagTagImageImagenameInternalServerError) GetPayload() *models.ErrorResponse {
	return o.Payload
}

func (o *DeleteMetadataTagTagImageImagenameInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

/*DeleteMetadataTagTagImageImagenameBody delete metadata tag tag image imagename body
swagger:model DeleteMetadataTagTagImageImagenameBody
*/
type DeleteMetadataTagTagImageImagenameBody struct {

	// default value
	Value string `json:"Value,omitempty"`

	// key
	Key string `json:"Key,omitempty"`
}

// Validate validates this delete metadata tag tag image imagename body
func (o *DeleteMetadataTagTagImageImagenameBody) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this delete metadata tag tag image imagename body based on context it is used
func (o *DeleteMetadataTagTagImageImagenameBody) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (o *DeleteMetadataTagTagImageImagenameBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *DeleteMetadataTagTagImageImagenameBody) UnmarshalBinary(b []byte) error {
	var res DeleteMetadataTagTagImageImagenameBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}
