// Code generated by go-swagger; DO NOT EDIT.

package metadata

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewDeleteMetadataTagTagImageImagenameParams creates a new DeleteMetadataTagTagImageImagenameParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewDeleteMetadataTagTagImageImagenameParams() *DeleteMetadataTagTagImageImagenameParams {
	return &DeleteMetadataTagTagImageImagenameParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewDeleteMetadataTagTagImageImagenameParamsWithTimeout creates a new DeleteMetadataTagTagImageImagenameParams object
// with the ability to set a timeout on a request.
func NewDeleteMetadataTagTagImageImagenameParamsWithTimeout(timeout time.Duration) *DeleteMetadataTagTagImageImagenameParams {
	return &DeleteMetadataTagTagImageImagenameParams{
		timeout: timeout,
	}
}

// NewDeleteMetadataTagTagImageImagenameParamsWithContext creates a new DeleteMetadataTagTagImageImagenameParams object
// with the ability to set a context for a request.
func NewDeleteMetadataTagTagImageImagenameParamsWithContext(ctx context.Context) *DeleteMetadataTagTagImageImagenameParams {
	return &DeleteMetadataTagTagImageImagenameParams{
		Context: ctx,
	}
}

// NewDeleteMetadataTagTagImageImagenameParamsWithHTTPClient creates a new DeleteMetadataTagTagImageImagenameParams object
// with the ability to set a custom HTTPClient for a request.
func NewDeleteMetadataTagTagImageImagenameParamsWithHTTPClient(client *http.Client) *DeleteMetadataTagTagImageImagenameParams {
	return &DeleteMetadataTagTagImageImagenameParams{
		HTTPClient: client,
	}
}

/* DeleteMetadataTagTagImageImagenameParams contains all the parameters to send to the API endpoint
   for the delete metadata tag tag image imagename operation.

   Typically these are written to a http.Request.
*/
type DeleteMetadataTagTagImageImagenameParams struct {

	// KeyValue.
	KeyValue DeleteMetadataTagTagImageImagenameBody

	// Imagename.
	Imagename string

	// Tag.
	Tag string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the delete metadata tag tag image imagename params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *DeleteMetadataTagTagImageImagenameParams) WithDefaults() *DeleteMetadataTagTagImageImagenameParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the delete metadata tag tag image imagename params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *DeleteMetadataTagTagImageImagenameParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the delete metadata tag tag image imagename params
func (o *DeleteMetadataTagTagImageImagenameParams) WithTimeout(timeout time.Duration) *DeleteMetadataTagTagImageImagenameParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the delete metadata tag tag image imagename params
func (o *DeleteMetadataTagTagImageImagenameParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the delete metadata tag tag image imagename params
func (o *DeleteMetadataTagTagImageImagenameParams) WithContext(ctx context.Context) *DeleteMetadataTagTagImageImagenameParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the delete metadata tag tag image imagename params
func (o *DeleteMetadataTagTagImageImagenameParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the delete metadata tag tag image imagename params
func (o *DeleteMetadataTagTagImageImagenameParams) WithHTTPClient(client *http.Client) *DeleteMetadataTagTagImageImagenameParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the delete metadata tag tag image imagename params
func (o *DeleteMetadataTagTagImageImagenameParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithKeyValue adds the keyValue to the delete metadata tag tag image imagename params
func (o *DeleteMetadataTagTagImageImagenameParams) WithKeyValue(keyValue DeleteMetadataTagTagImageImagenameBody) *DeleteMetadataTagTagImageImagenameParams {
	o.SetKeyValue(keyValue)
	return o
}

// SetKeyValue adds the keyValue to the delete metadata tag tag image imagename params
func (o *DeleteMetadataTagTagImageImagenameParams) SetKeyValue(keyValue DeleteMetadataTagTagImageImagenameBody) {
	o.KeyValue = keyValue
}

// WithImagename adds the imagename to the delete metadata tag tag image imagename params
func (o *DeleteMetadataTagTagImageImagenameParams) WithImagename(imagename string) *DeleteMetadataTagTagImageImagenameParams {
	o.SetImagename(imagename)
	return o
}

// SetImagename adds the imagename to the delete metadata tag tag image imagename params
func (o *DeleteMetadataTagTagImageImagenameParams) SetImagename(imagename string) {
	o.Imagename = imagename
}

// WithTag adds the tag to the delete metadata tag tag image imagename params
func (o *DeleteMetadataTagTagImageImagenameParams) WithTag(tag string) *DeleteMetadataTagTagImageImagenameParams {
	o.SetTag(tag)
	return o
}

// SetTag adds the tag to the delete metadata tag tag image imagename params
func (o *DeleteMetadataTagTagImageImagenameParams) SetTag(tag string) {
	o.Tag = tag
}

// WriteToRequest writes these params to a swagger request
func (o *DeleteMetadataTagTagImageImagenameParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if err := r.SetBodyParam(o.KeyValue); err != nil {
		return err
	}

	// path param imagename
	if err := r.SetPathParam("imagename", o.Imagename); err != nil {
		return err
	}

	// path param tag
	if err := r.SetPathParam("tag", o.Tag); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
