// Code generated by go-swagger; DO NOT EDIT.

package metadata

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetMetadataTagTagImageImagenameParams creates a new GetMetadataTagTagImageImagenameParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetMetadataTagTagImageImagenameParams() *GetMetadataTagTagImageImagenameParams {
	return &GetMetadataTagTagImageImagenameParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetMetadataTagTagImageImagenameParamsWithTimeout creates a new GetMetadataTagTagImageImagenameParams object
// with the ability to set a timeout on a request.
func NewGetMetadataTagTagImageImagenameParamsWithTimeout(timeout time.Duration) *GetMetadataTagTagImageImagenameParams {
	return &GetMetadataTagTagImageImagenameParams{
		timeout: timeout,
	}
}

// NewGetMetadataTagTagImageImagenameParamsWithContext creates a new GetMetadataTagTagImageImagenameParams object
// with the ability to set a context for a request.
func NewGetMetadataTagTagImageImagenameParamsWithContext(ctx context.Context) *GetMetadataTagTagImageImagenameParams {
	return &GetMetadataTagTagImageImagenameParams{
		Context: ctx,
	}
}

// NewGetMetadataTagTagImageImagenameParamsWithHTTPClient creates a new GetMetadataTagTagImageImagenameParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetMetadataTagTagImageImagenameParamsWithHTTPClient(client *http.Client) *GetMetadataTagTagImageImagenameParams {
	return &GetMetadataTagTagImageImagenameParams{
		HTTPClient: client,
	}
}

/* GetMetadataTagTagImageImagenameParams contains all the parameters to send to the API endpoint
   for the get metadata tag tag image imagename operation.

   Typically these are written to a http.Request.
*/
type GetMetadataTagTagImageImagenameParams struct {

	// Imagename.
	Imagename string

	// Tag.
	Tag string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get metadata tag tag image imagename params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetMetadataTagTagImageImagenameParams) WithDefaults() *GetMetadataTagTagImageImagenameParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get metadata tag tag image imagename params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetMetadataTagTagImageImagenameParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get metadata tag tag image imagename params
func (o *GetMetadataTagTagImageImagenameParams) WithTimeout(timeout time.Duration) *GetMetadataTagTagImageImagenameParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get metadata tag tag image imagename params
func (o *GetMetadataTagTagImageImagenameParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get metadata tag tag image imagename params
func (o *GetMetadataTagTagImageImagenameParams) WithContext(ctx context.Context) *GetMetadataTagTagImageImagenameParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get metadata tag tag image imagename params
func (o *GetMetadataTagTagImageImagenameParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get metadata tag tag image imagename params
func (o *GetMetadataTagTagImageImagenameParams) WithHTTPClient(client *http.Client) *GetMetadataTagTagImageImagenameParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get metadata tag tag image imagename params
func (o *GetMetadataTagTagImageImagenameParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithImagename adds the imagename to the get metadata tag tag image imagename params
func (o *GetMetadataTagTagImageImagenameParams) WithImagename(imagename string) *GetMetadataTagTagImageImagenameParams {
	o.SetImagename(imagename)
	return o
}

// SetImagename adds the imagename to the get metadata tag tag image imagename params
func (o *GetMetadataTagTagImageImagenameParams) SetImagename(imagename string) {
	o.Imagename = imagename
}

// WithTag adds the tag to the get metadata tag tag image imagename params
func (o *GetMetadataTagTagImageImagenameParams) WithTag(tag string) *GetMetadataTagTagImageImagenameParams {
	o.SetTag(tag)
	return o
}

// SetTag adds the tag to the get metadata tag tag image imagename params
func (o *GetMetadataTagTagImageImagenameParams) SetTag(tag string) {
	o.Tag = tag
}

// WriteToRequest writes these params to a swagger request
func (o *GetMetadataTagTagImageImagenameParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param imagename
	if err := r.SetPathParam("imagename", o.Imagename); err != nil {
		return err
	}

	// path param tag
	if err := r.SetPathParam("tag", o.Tag); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
