// Code generated by go-swagger; DO NOT EDIT.

package metadata

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"

	"docker_image_metadata_api/models"
)

// PostMetadataTagTagImageImagenameReader is a Reader for the PostMetadataTagTagImageImagename structure.
type PostMetadataTagTagImageImagenameReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PostMetadataTagTagImageImagenameReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 201:
		result := NewPostMetadataTagTagImageImagenameCreated()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 500:
		result := NewPostMetadataTagTagImageImagenameInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewPostMetadataTagTagImageImagenameCreated creates a PostMetadataTagTagImageImagenameCreated with default headers values
func NewPostMetadataTagTagImageImagenameCreated() *PostMetadataTagTagImageImagenameCreated {
	return &PostMetadataTagTagImageImagenameCreated{}
}

/* PostMetadataTagTagImageImagenameCreated describes a response with status code 201, with default header values.

Created
*/
type PostMetadataTagTagImageImagenameCreated struct {
}

func (o *PostMetadataTagTagImageImagenameCreated) Error() string {
	return fmt.Sprintf("[POST /metadata/tag/{tag}/image/{imagename}][%d] postMetadataTagTagImageImagenameCreated ", 201)
}

func (o *PostMetadataTagTagImageImagenameCreated) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewPostMetadataTagTagImageImagenameInternalServerError creates a PostMetadataTagTagImageImagenameInternalServerError with default headers values
func NewPostMetadataTagTagImageImagenameInternalServerError() *PostMetadataTagTagImageImagenameInternalServerError {
	return &PostMetadataTagTagImageImagenameInternalServerError{}
}

/* PostMetadataTagTagImageImagenameInternalServerError describes a response with status code 500, with default header values.

Internal Error Message
*/
type PostMetadataTagTagImageImagenameInternalServerError struct {
	Payload *models.ErrorResponse
}

func (o *PostMetadataTagTagImageImagenameInternalServerError) Error() string {
	return fmt.Sprintf("[POST /metadata/tag/{tag}/image/{imagename}][%d] postMetadataTagTagImageImagenameInternalServerError  %+v", 500, o.Payload)
}
func (o *PostMetadataTagTagImageImagenameInternalServerError) GetPayload() *models.ErrorResponse {
	return o.Payload
}

func (o *PostMetadataTagTagImageImagenameInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

/*PostMetadataTagTagImageImagenameBody post metadata tag tag image imagename body
swagger:model PostMetadataTagTagImageImagenameBody
*/
type PostMetadataTagTagImageImagenameBody struct {

	// default value
	Value string `json:"Value,omitempty"`

	// key
	Key string `json:"Key,omitempty"`
}

// Validate validates this post metadata tag tag image imagename body
func (o *PostMetadataTagTagImageImagenameBody) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this post metadata tag tag image imagename body based on context it is used
func (o *PostMetadataTagTagImageImagenameBody) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (o *PostMetadataTagTagImageImagenameBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *PostMetadataTagTagImageImagenameBody) UnmarshalBinary(b []byte) error {
	var res PostMetadataTagTagImageImagenameBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}
