// Code generated by go-swagger; DO NOT EDIT.

package metadata

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewPutMetadataTagTagImageImagenameParams creates a new PutMetadataTagTagImageImagenameParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewPutMetadataTagTagImageImagenameParams() *PutMetadataTagTagImageImagenameParams {
	return &PutMetadataTagTagImageImagenameParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewPutMetadataTagTagImageImagenameParamsWithTimeout creates a new PutMetadataTagTagImageImagenameParams object
// with the ability to set a timeout on a request.
func NewPutMetadataTagTagImageImagenameParamsWithTimeout(timeout time.Duration) *PutMetadataTagTagImageImagenameParams {
	return &PutMetadataTagTagImageImagenameParams{
		timeout: timeout,
	}
}

// NewPutMetadataTagTagImageImagenameParamsWithContext creates a new PutMetadataTagTagImageImagenameParams object
// with the ability to set a context for a request.
func NewPutMetadataTagTagImageImagenameParamsWithContext(ctx context.Context) *PutMetadataTagTagImageImagenameParams {
	return &PutMetadataTagTagImageImagenameParams{
		Context: ctx,
	}
}

// NewPutMetadataTagTagImageImagenameParamsWithHTTPClient creates a new PutMetadataTagTagImageImagenameParams object
// with the ability to set a custom HTTPClient for a request.
func NewPutMetadataTagTagImageImagenameParamsWithHTTPClient(client *http.Client) *PutMetadataTagTagImageImagenameParams {
	return &PutMetadataTagTagImageImagenameParams{
		HTTPClient: client,
	}
}

/* PutMetadataTagTagImageImagenameParams contains all the parameters to send to the API endpoint
   for the put metadata tag tag image imagename operation.

   Typically these are written to a http.Request.
*/
type PutMetadataTagTagImageImagenameParams struct {

	// KeyValue.
	KeyValue PutMetadataTagTagImageImagenameBody

	// Imagename.
	Imagename string

	// Tag.
	Tag string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the put metadata tag tag image imagename params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PutMetadataTagTagImageImagenameParams) WithDefaults() *PutMetadataTagTagImageImagenameParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the put metadata tag tag image imagename params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PutMetadataTagTagImageImagenameParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the put metadata tag tag image imagename params
func (o *PutMetadataTagTagImageImagenameParams) WithTimeout(timeout time.Duration) *PutMetadataTagTagImageImagenameParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the put metadata tag tag image imagename params
func (o *PutMetadataTagTagImageImagenameParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the put metadata tag tag image imagename params
func (o *PutMetadataTagTagImageImagenameParams) WithContext(ctx context.Context) *PutMetadataTagTagImageImagenameParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the put metadata tag tag image imagename params
func (o *PutMetadataTagTagImageImagenameParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the put metadata tag tag image imagename params
func (o *PutMetadataTagTagImageImagenameParams) WithHTTPClient(client *http.Client) *PutMetadataTagTagImageImagenameParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the put metadata tag tag image imagename params
func (o *PutMetadataTagTagImageImagenameParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithKeyValue adds the keyValue to the put metadata tag tag image imagename params
func (o *PutMetadataTagTagImageImagenameParams) WithKeyValue(keyValue PutMetadataTagTagImageImagenameBody) *PutMetadataTagTagImageImagenameParams {
	o.SetKeyValue(keyValue)
	return o
}

// SetKeyValue adds the keyValue to the put metadata tag tag image imagename params
func (o *PutMetadataTagTagImageImagenameParams) SetKeyValue(keyValue PutMetadataTagTagImageImagenameBody) {
	o.KeyValue = keyValue
}

// WithImagename adds the imagename to the put metadata tag tag image imagename params
func (o *PutMetadataTagTagImageImagenameParams) WithImagename(imagename string) *PutMetadataTagTagImageImagenameParams {
	o.SetImagename(imagename)
	return o
}

// SetImagename adds the imagename to the put metadata tag tag image imagename params
func (o *PutMetadataTagTagImageImagenameParams) SetImagename(imagename string) {
	o.Imagename = imagename
}

// WithTag adds the tag to the put metadata tag tag image imagename params
func (o *PutMetadataTagTagImageImagenameParams) WithTag(tag string) *PutMetadataTagTagImageImagenameParams {
	o.SetTag(tag)
	return o
}

// SetTag adds the tag to the put metadata tag tag image imagename params
func (o *PutMetadataTagTagImageImagenameParams) SetTag(tag string) {
	o.Tag = tag
}

// WriteToRequest writes these params to a swagger request
func (o *PutMetadataTagTagImageImagenameParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if err := r.SetBodyParam(o.KeyValue); err != nil {
		return err
	}

	// path param imagename
	if err := r.SetPathParam("imagename", o.Imagename); err != nil {
		return err
	}

	// path param tag
	if err := r.SetPathParam("tag", o.Tag); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
