// Code generated by go-swagger; DO NOT EDIT.

package metadata

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"docker_image_metadata_api/models"
)

// DeleteMetadataImageImageNameTagTagNameKeysOKCode is the HTTP code returned for type DeleteMetadataImageImageNameTagTagNameKeysOK
const DeleteMetadataImageImageNameTagTagNameKeysOKCode int = 200

/*DeleteMetadataImageImageNameTagTagNameKeysOK Successfully removed

swagger:response deleteMetadataImageImageNameTagTagNameKeysOK
*/
type DeleteMetadataImageImageNameTagTagNameKeysOK struct {
}

// NewDeleteMetadataImageImageNameTagTagNameKeysOK creates DeleteMetadataImageImageNameTagTagNameKeysOK with default headers values
func NewDeleteMetadataImageImageNameTagTagNameKeysOK() *DeleteMetadataImageImageNameTagTagNameKeysOK {

	return &DeleteMetadataImageImageNameTagTagNameKeysOK{}
}

// WriteResponse to the client
func (o *DeleteMetadataImageImageNameTagTagNameKeysOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(200)
}

// DeleteMetadataImageImageNameTagTagNameKeysNotFoundCode is the HTTP code returned for type DeleteMetadataImageImageNameTagTagNameKeysNotFound
const DeleteMetadataImageImageNameTagTagNameKeysNotFoundCode int = 404

/*DeleteMetadataImageImageNameTagTagNameKeysNotFound Not Found

swagger:response deleteMetadataImageImageNameTagTagNameKeysNotFound
*/
type DeleteMetadataImageImageNameTagTagNameKeysNotFound struct {

	/*
	  In: Body
	*/
	Payload *models.NotFoundResponse `json:"body,omitempty"`
}

// NewDeleteMetadataImageImageNameTagTagNameKeysNotFound creates DeleteMetadataImageImageNameTagTagNameKeysNotFound with default headers values
func NewDeleteMetadataImageImageNameTagTagNameKeysNotFound() *DeleteMetadataImageImageNameTagTagNameKeysNotFound {

	return &DeleteMetadataImageImageNameTagTagNameKeysNotFound{}
}

// WithPayload adds the payload to the delete metadata image image name tag tag name keys not found response
func (o *DeleteMetadataImageImageNameTagTagNameKeysNotFound) WithPayload(payload *models.NotFoundResponse) *DeleteMetadataImageImageNameTagTagNameKeysNotFound {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the delete metadata image image name tag tag name keys not found response
func (o *DeleteMetadataImageImageNameTagTagNameKeysNotFound) SetPayload(payload *models.NotFoundResponse) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *DeleteMetadataImageImageNameTagTagNameKeysNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(404)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// DeleteMetadataImageImageNameTagTagNameKeysInternalServerErrorCode is the HTTP code returned for type DeleteMetadataImageImageNameTagTagNameKeysInternalServerError
const DeleteMetadataImageImageNameTagTagNameKeysInternalServerErrorCode int = 500

/*DeleteMetadataImageImageNameTagTagNameKeysInternalServerError Internal Error Message

swagger:response deleteMetadataImageImageNameTagTagNameKeysInternalServerError
*/
type DeleteMetadataImageImageNameTagTagNameKeysInternalServerError struct {

	/*
	  In: Body
	*/
	Payload *models.ErrorResponse `json:"body,omitempty"`
}

// NewDeleteMetadataImageImageNameTagTagNameKeysInternalServerError creates DeleteMetadataImageImageNameTagTagNameKeysInternalServerError with default headers values
func NewDeleteMetadataImageImageNameTagTagNameKeysInternalServerError() *DeleteMetadataImageImageNameTagTagNameKeysInternalServerError {

	return &DeleteMetadataImageImageNameTagTagNameKeysInternalServerError{}
}

// WithPayload adds the payload to the delete metadata image image name tag tag name keys internal server error response
func (o *DeleteMetadataImageImageNameTagTagNameKeysInternalServerError) WithPayload(payload *models.ErrorResponse) *DeleteMetadataImageImageNameTagTagNameKeysInternalServerError {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the delete metadata image image name tag tag name keys internal server error response
func (o *DeleteMetadataImageImageNameTagTagNameKeysInternalServerError) SetPayload(payload *models.ErrorResponse) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *DeleteMetadataImageImageNameTagTagNameKeysInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(500)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
