// Code generated by go-swagger; DO NOT EDIT.

package metadata

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"context"
	"net/http"

	"github.com/go-openapi/runtime/middleware"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// DeleteMetadataImageTagKeysHandlerFunc turns a function with the right signature into a delete metadata image tag keys handler
type DeleteMetadataImageTagKeysHandlerFunc func(DeleteMetadataImageTagKeysParams) middleware.Responder

// Handle executing the request and returning a response
func (fn DeleteMetadataImageTagKeysHandlerFunc) Handle(params DeleteMetadataImageTagKeysParams) middleware.Responder {
	return fn(params)
}

// DeleteMetadataImageTagKeysHandler interface for that can handle valid delete metadata image tag keys params
type DeleteMetadataImageTagKeysHandler interface {
	Handle(DeleteMetadataImageTagKeysParams) middleware.Responder
}

// NewDeleteMetadataImageTagKeys creates a new http.Handler for the delete metadata image tag keys operation
func NewDeleteMetadataImageTagKeys(ctx *middleware.Context, handler DeleteMetadataImageTagKeysHandler) *DeleteMetadataImageTagKeys {
	return &DeleteMetadataImageTagKeys{Context: ctx, Handler: handler}
}

/* DeleteMetadataImageTagKeys swagger:route DELETE /metadata/image/tag/keys Metadata deleteMetadataImageTagKeys

Remove key from metadata

Remove metadata key

*/
type DeleteMetadataImageTagKeys struct {
	Context *middleware.Context
	Handler DeleteMetadataImageTagKeysHandler
}

func (o *DeleteMetadataImageTagKeys) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewDeleteMetadataImageTagKeysParams()
	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}

// DeleteMetadataImageTagKeysBody delete metadata image tag keys body
//
// swagger:model DeleteMetadataImageTagKeysBody
type DeleteMetadataImageTagKeysBody struct {

	// image name
	ImageName string `json:"ImageName,omitempty"`

	// key
	Key string `json:"Key,omitempty"`

	// tag name
	TagName string `json:"TagName,omitempty"`
}

// Validate validates this delete metadata image tag keys body
func (o *DeleteMetadataImageTagKeysBody) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this delete metadata image tag keys body based on context it is used
func (o *DeleteMetadataImageTagKeysBody) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (o *DeleteMetadataImageTagKeysBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *DeleteMetadataImageTagKeysBody) UnmarshalBinary(b []byte) error {
	var res DeleteMetadataImageTagKeysBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}
