// Code generated by go-swagger; DO NOT EDIT.

package metadata

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"context"
	"net/http"

	"github.com/go-openapi/runtime/middleware"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// PostMetadataImageTagKeysHandlerFunc turns a function with the right signature into a post metadata image tag keys handler
type PostMetadataImageTagKeysHandlerFunc func(PostMetadataImageTagKeysParams) middleware.Responder

// Handle executing the request and returning a response
func (fn PostMetadataImageTagKeysHandlerFunc) Handle(params PostMetadataImageTagKeysParams) middleware.Responder {
	return fn(params)
}

// PostMetadataImageTagKeysHandler interface for that can handle valid post metadata image tag keys params
type PostMetadataImageTagKeysHandler interface {
	Handle(PostMetadataImageTagKeysParams) middleware.Responder
}

// NewPostMetadataImageTagKeys creates a new http.Handler for the post metadata image tag keys operation
func NewPostMetadataImageTagKeys(ctx *middleware.Context, handler PostMetadataImageTagKeysHandler) *PostMetadataImageTagKeys {
	return &PostMetadataImageTagKeys{Context: ctx, Handler: handler}
}

/* PostMetadataImageTagKeys swagger:route POST /metadata/image/tag/keys Metadata postMetadataImageTagKeys

Create new key in metadata

Create new metadata key and (optional) new default value

*/
type PostMetadataImageTagKeys struct {
	Context *middleware.Context
	Handler PostMetadataImageTagKeysHandler
}

func (o *PostMetadataImageTagKeys) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewPostMetadataImageTagKeysParams()
	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}

// PostMetadataImageTagKeysBody post metadata image tag keys body
//
// swagger:model PostMetadataImageTagKeysBody
type PostMetadataImageTagKeysBody struct {

	// default value
	Value *string `json:"Value,omitempty"`

	// image name
	ImageName string `json:"ImageName,omitempty"`

	// key
	Key string `json:"Key,omitempty"`

	// tag name
	TagName string `json:"TagName,omitempty"`
}

// Validate validates this post metadata image tag keys body
func (o *PostMetadataImageTagKeysBody) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this post metadata image tag keys body based on context it is used
func (o *PostMetadataImageTagKeysBody) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (o *PostMetadataImageTagKeysBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *PostMetadataImageTagKeysBody) UnmarshalBinary(b []byte) error {
	var res PostMetadataImageTagKeysBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}
