// Code generated by go-swagger; DO NOT EDIT.

package metadata

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"docker_image_metadata_api/models"
)

// PutMetadataImageImageNameTagTagNameKeysOKCode is the HTTP code returned for type PutMetadataImageImageNameTagTagNameKeysOK
const PutMetadataImageImageNameTagTagNameKeysOKCode int = 200

/*PutMetadataImageImageNameTagTagNameKeysOK Successfully updated

swagger:response putMetadataImageImageNameTagTagNameKeysOK
*/
type PutMetadataImageImageNameTagTagNameKeysOK struct {
}

// NewPutMetadataImageImageNameTagTagNameKeysOK creates PutMetadataImageImageNameTagTagNameKeysOK with default headers values
func NewPutMetadataImageImageNameTagTagNameKeysOK() *PutMetadataImageImageNameTagTagNameKeysOK {

	return &PutMetadataImageImageNameTagTagNameKeysOK{}
}

// WriteResponse to the client
func (o *PutMetadataImageImageNameTagTagNameKeysOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(200)
}

// PutMetadataImageImageNameTagTagNameKeysInternalServerErrorCode is the HTTP code returned for type PutMetadataImageImageNameTagTagNameKeysInternalServerError
const PutMetadataImageImageNameTagTagNameKeysInternalServerErrorCode int = 500

/*PutMetadataImageImageNameTagTagNameKeysInternalServerError Internal Error Message

swagger:response putMetadataImageImageNameTagTagNameKeysInternalServerError
*/
type PutMetadataImageImageNameTagTagNameKeysInternalServerError struct {

	/*
	  In: Body
	*/
	Payload *models.ErrorResponse `json:"body,omitempty"`
}

// NewPutMetadataImageImageNameTagTagNameKeysInternalServerError creates PutMetadataImageImageNameTagTagNameKeysInternalServerError with default headers values
func NewPutMetadataImageImageNameTagTagNameKeysInternalServerError() *PutMetadataImageImageNameTagTagNameKeysInternalServerError {

	return &PutMetadataImageImageNameTagTagNameKeysInternalServerError{}
}

// WithPayload adds the payload to the put metadata image image name tag tag name keys internal server error response
func (o *PutMetadataImageImageNameTagTagNameKeysInternalServerError) WithPayload(payload *models.ErrorResponse) *PutMetadataImageImageNameTagTagNameKeysInternalServerError {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the put metadata image image name tag tag name keys internal server error response
func (o *PutMetadataImageImageNameTagTagNameKeysInternalServerError) SetPayload(payload *models.ErrorResponse) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PutMetadataImageImageNameTagTagNameKeysInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(500)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
