// Code generated by go-swagger; DO NOT EDIT.

package metadata

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"context"
	"net/http"

	"github.com/go-openapi/runtime/middleware"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// PutMetadataImageImageNameTagTagNameKeysHandlerFunc turns a function with the right signature into a put metadata image image name tag tag name keys handler
type PutMetadataImageImageNameTagTagNameKeysHandlerFunc func(PutMetadataImageImageNameTagTagNameKeysParams) middleware.Responder

// Handle executing the request and returning a response
func (fn PutMetadataImageImageNameTagTagNameKeysHandlerFunc) Handle(params PutMetadataImageImageNameTagTagNameKeysParams) middleware.Responder {
	return fn(params)
}

// PutMetadataImageImageNameTagTagNameKeysHandler interface for that can handle valid put metadata image image name tag tag name keys params
type PutMetadataImageImageNameTagTagNameKeysHandler interface {
	Handle(PutMetadataImageImageNameTagTagNameKeysParams) middleware.Responder
}

// NewPutMetadataImageImageNameTagTagNameKeys creates a new http.Handler for the put metadata image image name tag tag name keys operation
func NewPutMetadataImageImageNameTagTagNameKeys(ctx *middleware.Context, handler PutMetadataImageImageNameTagTagNameKeysHandler) *PutMetadataImageImageNameTagTagNameKeys {
	return &PutMetadataImageImageNameTagTagNameKeys{Context: ctx, Handler: handler}
}

/* PutMetadataImageImageNameTagTagNameKeys swagger:route PUT /metadata/image/{ImageName}/tag/{TagName}/keys Metadata putMetadataImageImageNameTagTagNameKeys

Update default value of specified key

Update default value of specified key

*/
type PutMetadataImageImageNameTagTagNameKeys struct {
	Context *middleware.Context
	Handler PutMetadataImageImageNameTagTagNameKeysHandler
}

func (o *PutMetadataImageImageNameTagTagNameKeys) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewPutMetadataImageImageNameTagTagNameKeysParams()
	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}

// PutMetadataImageImageNameTagTagNameKeysBody put metadata image image name tag tag name keys body
//
// swagger:model PutMetadataImageImageNameTagTagNameKeysBody
type PutMetadataImageImageNameTagTagNameKeysBody struct {

	// default value
	Value string `json:"Value,omitempty"`

	// key
	Key string `json:"Key,omitempty"`
}

// Validate validates this put metadata image image name tag tag name keys body
func (o *PutMetadataImageImageNameTagTagNameKeysBody) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this put metadata image image name tag tag name keys body based on context it is used
func (o *PutMetadataImageImageNameTagTagNameKeysBody) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (o *PutMetadataImageImageNameTagTagNameKeysBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *PutMetadataImageImageNameTagTagNameKeysBody) UnmarshalBinary(b []byte) error {
	var res PutMetadataImageImageNameTagTagNameKeysBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}
