// Code generated by go-swagger; DO NOT EDIT.

package image_tag

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"docker_image_metadata_api/models"
)

// DeleteMetadataImageTagOKCode is the HTTP code returned for type DeleteMetadataImageTagOK
const DeleteMetadataImageTagOKCode int = 200

/*DeleteMetadataImageTagOK Erased

swagger:response deleteMetadataImageTagOK
*/
type DeleteMetadataImageTagOK struct {
}

// NewDeleteMetadataImageTagOK creates DeleteMetadataImageTagOK with default headers values
func NewDeleteMetadataImageTagOK() *DeleteMetadataImageTagOK {

	return &DeleteMetadataImageTagOK{}
}

// WriteResponse to the client
func (o *DeleteMetadataImageTagOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(200)
}

// DeleteMetadataImageTagNotFoundCode is the HTTP code returned for type DeleteMetadataImageTagNotFound
const DeleteMetadataImageTagNotFoundCode int = 404

/*DeleteMetadataImageTagNotFound Image with tag not found

swagger:response deleteMetadataImageTagNotFound
*/
type DeleteMetadataImageTagNotFound struct {

	/*
	  In: Body
	*/
	Payload *models.NotFoundResponse `json:"body,omitempty"`
}

// NewDeleteMetadataImageTagNotFound creates DeleteMetadataImageTagNotFound with default headers values
func NewDeleteMetadataImageTagNotFound() *DeleteMetadataImageTagNotFound {

	return &DeleteMetadataImageTagNotFound{}
}

// WithPayload adds the payload to the delete metadata image tag not found response
func (o *DeleteMetadataImageTagNotFound) WithPayload(payload *models.NotFoundResponse) *DeleteMetadataImageTagNotFound {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the delete metadata image tag not found response
func (o *DeleteMetadataImageTagNotFound) SetPayload(payload *models.NotFoundResponse) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *DeleteMetadataImageTagNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(404)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// DeleteMetadataImageTagInternalServerErrorCode is the HTTP code returned for type DeleteMetadataImageTagInternalServerError
const DeleteMetadataImageTagInternalServerErrorCode int = 500

/*DeleteMetadataImageTagInternalServerError Internal Error Message

swagger:response deleteMetadataImageTagInternalServerError
*/
type DeleteMetadataImageTagInternalServerError struct {

	/*
	  In: Body
	*/
	Payload *models.ErrorResponse `json:"body,omitempty"`
}

// NewDeleteMetadataImageTagInternalServerError creates DeleteMetadataImageTagInternalServerError with default headers values
func NewDeleteMetadataImageTagInternalServerError() *DeleteMetadataImageTagInternalServerError {

	return &DeleteMetadataImageTagInternalServerError{}
}

// WithPayload adds the payload to the delete metadata image tag internal server error response
func (o *DeleteMetadataImageTagInternalServerError) WithPayload(payload *models.ErrorResponse) *DeleteMetadataImageTagInternalServerError {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the delete metadata image tag internal server error response
func (o *DeleteMetadataImageTagInternalServerError) SetPayload(payload *models.ErrorResponse) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *DeleteMetadataImageTagInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(500)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
