// Code generated by go-swagger; DO NOT EDIT.

package image_tag

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"context"
	"net/http"

	"github.com/go-openapi/runtime/middleware"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// PostMetadataHandlerFunc turns a function with the right signature into a post metadata handler
type PostMetadataHandlerFunc func(PostMetadataParams) middleware.Responder

// Handle executing the request and returning a response
func (fn PostMetadataHandlerFunc) Handle(params PostMetadataParams) middleware.Responder {
	return fn(params)
}

// PostMetadataHandler interface for that can handle valid post metadata params
type PostMetadataHandler interface {
	Handle(PostMetadataParams) middleware.Responder
}

// NewPostMetadata creates a new http.Handler for the post metadata operation
func NewPostMetadata(ctx *middleware.Context, handler PostMetadataHandler) *PostMetadata {
	return &PostMetadata{Context: ctx, Handler: handler}
}

/* PostMetadata swagger:route POST /metadata ImageTag postMetadata

Register image with tag

Register and verify if the image exists in docker registry

*/
type PostMetadata struct {
	Context *middleware.Context
	Handler PostMetadataHandler
}

func (o *PostMetadata) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewPostMetadataParams()
	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}

// PostMetadataBody post metadata body
//
// swagger:model PostMetadataBody
type PostMetadataBody struct {

	// image name
	ImageName string `json:"ImageName,omitempty"`

	// tag name
	TagName string `json:"TagName,omitempty"`
}

// Validate validates this post metadata body
func (o *PostMetadataBody) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this post metadata body based on context it is used
func (o *PostMetadataBody) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (o *PostMetadataBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *PostMetadataBody) UnmarshalBinary(b []byte) error {
	var res PostMetadataBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}
