// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// DeletedTagResponse deleted tag response
//
// swagger:model DeletedTagResponse
type DeletedTagResponse struct {

	// image
	Image string `json:"Image,omitempty"`

	// message
	Message string `json:"Message,omitempty"`

	// tag
	Tag string `json:"Tag,omitempty"`
}

// Validate validates this deleted tag response
func (m *DeletedTagResponse) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this deleted tag response based on context it is used
func (m *DeletedTagResponse) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *DeletedTagResponse) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *DeletedTagResponse) UnmarshalBinary(b []byte) error {
	var res DeletedTagResponse
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
