// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// DeletedKeyResponse deleted key response
//
// swagger:model DeletedKeyResponse
type DeletedKeyResponse struct {

	// image
	Image string `json:"Image,omitempty"`

	// key
	Key string `json:"Key,omitempty"`

	// tag
	Tag string `json:"Tag,omitempty"`
}

// Validate validates this deleted key response
func (m *DeletedKeyResponse) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this deleted key response based on context it is used
func (m *DeletedKeyResponse) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *DeletedKeyResponse) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *DeletedKeyResponse) UnmarshalBinary(b []byte) error {
	var res DeletedKeyResponse
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
