// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// FailedDependency failed dependency
//
// swagger:model FailedDependency
type FailedDependency struct {

	// message
	Message string `json:"Message,omitempty"`
}

// Validate validates this failed dependency
func (m *FailedDependency) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this failed dependency based on context it is used
func (m *FailedDependency) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *FailedDependency) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *FailedDependency) UnmarshalBinary(b []byte) error {
	var res FailedDependency
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
