// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
)

// ListOfImages list of images
//
// swagger:model ListOfImages
type ListOfImages []string

// Validate validates this list of images
func (m ListOfImages) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this list of images based on context it is used
func (m ListOfImages) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}
