// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// MetadataObj metadata obj
//
// swagger:model MetadataObj
type MetadataObj struct {

	// default value
	Value interface{} `json:"Value,omitempty"`

	// key
	Key string `json:"Key,omitempty"`
}

// Validate validates this metadata obj
func (m *MetadataObj) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this metadata obj based on context it is used
func (m *MetadataObj) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *MetadataObj) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *MetadataObj) UnmarshalBinary(b []byte) error {
	var res MetadataObj
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
